// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlG2glNY3njAvAyJ7eEMeMtLg4Wcfg8rI',
    appId: '1:1068873884023:web:176aee37f04eb62fa28172',
    messagingSenderId: '1068873884023',
    projectId: 'programafono-7be09',
    authDomain: 'programafono-7be09.firebaseapp.com',
    storageBucket: 'programafono-7be09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIoYqmaFMuUD4OxGBBF9IqllrQhkQ6InM',
    appId: '1:1068873884023:android:ebd48cfe8affc99da28172',
    messagingSenderId: '1068873884023',
    projectId: 'programafono-7be09',
    storageBucket: 'programafono-7be09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8WxWyljnLxRq9HXI-QtDLDpyzfEBV2Nk',
    appId: '1:1068873884023:ios:c99b6a269cb9c6e9a28172',
    messagingSenderId: '1068873884023',
    projectId: 'programafono-7be09',
    storageBucket: 'programafono-7be09.appspot.com',
    iosBundleId: 'com.example.programafono',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8WxWyljnLxRq9HXI-QtDLDpyzfEBV2Nk',
    appId: '1:1068873884023:ios:608d49a5d56a084aa28172',
    messagingSenderId: '1068873884023',
    projectId: 'programafono-7be09',
    storageBucket: 'programafono-7be09.appspot.com',
    iosBundleId: 'com.example.programafono.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyAlG2glNY3njAvAyJ7eEMeMtLg4Wcfg8rI",
    authDomain: "programafono-7be09.firebaseapp.com",
    projectId: "programafono-7be09",
    storageBucket: "programafono-7be09.appspot.com",
    messagingSenderId: "1068873884023",
    appId: "1:1068873884023:web:85a43160ffc1ca25a28172"
  );
}
