# Mudar Nome no Android: android/app/main/AndroidManifest.xml
# Mudar Nome no iOS: ios/runner/info.plist -> CFBundleName

name: fonocare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-87.0.dev <4.0.0'

# flutter pub upgrade --major-versions
#flutter upgrade
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  firebase_core: ^3.3.0
  shared_preferences: ^2.3.1
  google_sign_in: ^6.2.1
  brasil_fields: ^1.15.0
  image_picker: ^1.1.2
  flutter_localization: ^0.2.1
  syncfusion_flutter_calendar: ^26.2.8
  search_cep: ^4.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  mask_text_input_formatter: ^2.9.0
  url_launcher: ^6.3.0
  toggle_switch: ^2.3.0
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  window_manager: ^0.3.9
  pdf: ^3.11.0
  path_provider: ^2.1.4
  file_picker: ^8.0.7
  open_file: ^3.3.2
  flutter_switch: ^0.3.2
  path: ^1.9.0
  http: ^1.2.2
  provider: ^6.1.2

flutter_native_splash:
  color: #B4CABB
  image: images/icon.png
  android: true
  ios: true
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter_icons:
  image_path: images/icon.png
  android:
    generate: true
    icon_size: 48
  image_path_android: images/icon.png
  ios: true
  image_path_ios: images/icon.png
  remove_alpha_ios: true
  web:
    generate: true
    image_path: images/icon.png
    background_color: #B4CABB
    theme_color: #F9D5D2
  windows:
    generate: true
    image_path: images/icon.png
    icon_size: 48

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - images/social_media/google.png
    - images/social_media/phone.png
    - images/social_media/whatsapp.png
    - images/logo.png
    - images/icon.png
    - images/icons/profileBoy.png
    - images/icons/profileGirl.png

  fonts:
    - family: La Belle Aurore
      fonts:
        - asset: fonts/LaBelleAurore-Regular.ttf
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
    - family: Adage
      fonts:
        - asset: fonts/Adage-Script-JF.ttf
