# Mudar Nome no Android: android/app/main/AndroidManifest.xml
# Mudar Nome no iOS: ios/runner/info.plist -> CFBundleName

name: fonocare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-87.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1
  firebase_storage: ^11.4.1
  firebase_core: ^2.21.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.1.5
  brasil_fields: ^1.14.0
  image_picker: ^1.0.4
  syncfusion_flutter_calendar: ^23.1.44
  flutter_localization: ^0.1.14
  search_cep: ^4.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.4
  mask_text_input_formatter: ^2.5.0
  url_launcher: ^6.1.14
  toggle_switch: ^2.1.0
  font_awesome_flutter: ^10.6.0
  intl: ^0.18.1
  window_manager: ^0.3.7
  pdf: ^3.10.4
  path_provider: ^2.1.1
  file_picker: ^6.0.0
  open_file: ^3.3.2
  syncfusion_flutter_pdfviewer: ^23.1.43

flutter_native_splash:
  color: #B4CABB
  image: images/icon.png
  android: true
  ios: true
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: images/icon.png
  android:
    generate: true
    icon_size: 48
  image_path_android: images/icon.png
  ios: true
  image_path_ios: images/icon.png
  remove_alpha_ios: true
  web:
    generate: true
    image_path: images/icon.png
    background_color: #B4CABB
    theme_color: #F9D5D2
  windows:
    generate: true
    image_path: images/icon.png
    icon_size: 48

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - images/social_media/google.png
    - images/social_media/phone.png
    - images/social_media/whatsapp.png
    - images/logo.png
    - images/icon.png
    - images/icons/profileBoy.png
    - images/icons/profileGirl.png

  fonts:
    - family: La Belle Aurore
      fonts:
        - asset: fonts/LaBelleAurore-Regular.ttf
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
    - family: Adage
      fonts:
        - asset: fonts/Adage-Script-JF.ttf
